services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
      POSTGRES_DB: musicdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  backend:
    build: ./backend
    command: air
    environment:
      DATABASE_URL: postgres://music:music@db:5432/musicdb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@mq:5672/
    depends_on:
      - db
      - mq
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    restart: unless-stopped

  # downloader-tidal:
  #   build: ./downloader-tidal
  #   environment:
  #     RABBITMQ_URL: amqp://guest:guest@mq:5672/
  #   depends_on:
  #     - mq
  #   volumes:
  #     - ./downloader-tidal:/app

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - API_URL=http://backend:8080/
      - SESSION_SECRET=meowmeowmeow
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
