services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
      POSTGRES_DB: musicdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d musicdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: 
      context: ./backend
      dockerfile: ./backend/Dockerfile.dev
    command: air
    environment:
      DATABASE_URL: postgres://music:music@db:5432/musicdb?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@mq:5672/
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fs -X POST http://localhost:8080 \
          -H 'Content-Type: application/json' \
          -d '{\"query\":\"query { __typename }\"}' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  tidal:
    build: 
      context: ./tidal
      dockerfile: ./tidal/Dockerfile.dev
    command: bash -c "pip install watchdog && watchmedo auto-restart --directory=./ --pattern='*.py' --recursive python main.py"
    environment:
      RABBITMQ_URL: amqp://guest:guest@mq:5672/
      CONFIG_SERVICE_URL: http://backend:8080
      PYTHONUNBUFFERED: 1
    depends_on:
      backend:
        condition: service_healthy
      mq:
        condition: service_healthy
    volumes:
      - ./tidal:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      # - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - INTERNAL_API_URL=backend:8080/
      - PUBLIC_API_URL=localhost:8080/
      - SESSION_SECRET=meowmeowmeow
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
