networks:
  database:
  backend:

volumes:
  pgdata:

services:
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d musicdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: NMJ316ptAbAWdzT7
      POSTGRES_DB: musicdb

  rabbitmq:
    image: rabbitmq:3-alpine # rabbitmq:3-management-alpine for web UI
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: music
      RABBITMQ_DEFAULT_PASS: 7ni8KtK59QtRkiZy

  backend:
    image: ghcr.io/cznavody19/music-manager-backend:main
    restart: unless-stopped
    networks:
      - database
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -fs -X POST http://localhost:8080 \
          -H 'Content-Type: application/json' \
          -d '{\"query\":\"query { __typename }\"}' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      DB_CONNECTIONURI: postgres://music:NMJ316ptAbAWdzT7@database:5432/musicdb?sslmode=disable
      DB_RUNMIGRATION: true
      MQ_CONNECTIONURI: amqp://music:7ni8KtK59QtRkiZy@rabbitmq:5672/
      SERVER_PLAYGROUNDENABLE: false
      SERVER_INTROSPECTIONENABLE: false
      SERVER_TOKENCHECKENABLE: true
      SERVER_RUNCRON: true
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/cznavody19/music-manager-frontend:main
    restart: unless-stopped
    networks:
      - backend
    environment:
      - INTERNAL_API_URL=backend:8080/
      - PUBLIC_API_URL=localhost:8080/
      - SESSION_SECRET=52nV2OwHKf8iwq2x
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"

  tidal:
    image: ghcr.io/cznavody19/music-manager-tidal:main
    restart: unless-stopped
    networks:
      - backend
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_URL: amqp://music:7ni8KtK59QtRkiZy@rabbitmq:5672/
      CONFIG_SERVICE_URL: http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy